import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        "tertiary-fixed": "#ffdf99",
        "surface-dim": "#0f1415",
        "on-secondary-container": "#bfb6df",
        "on-tertiary": "#3f2e00",
        "on-error": "#690005",
        "inverse-surface": "#dee3e4",
        "secondary-container": "#4d4769",
        "primary-fixed": "#90f1ff",
        "surface-tint": "#5bd7e7",
        "surface": "#0f1415",
        "surface-container-lowest": "#090f10",
        "inverse-on-surface": "#2c3132",
        "outline-variant": "#3d494b",
        "on-tertiary-fixed-variant": "#5a4300",
        "primary-container": "#6ee8f8",
        "on-primary": "#00363c",
        "on-surface": "#dee3e4",
        "outline": "#869395",
        "tertiary-container": "#ffd161",
        "on-secondary": "#322c4c",
        "inverse-primary": "#006973",
        "surface-variant": "#303637",
        "surface-container": "#1b2121",
        "tertiary": "#fff2db",
        "on-background": "#dee3e4",
        "neon-cyan": "#6EE8F8",
        "error": "#ffb4ab",
        "on-primary-container": "#006771",
        "secondary": "#cac1ea",
        "surface-bright": "#343a3b",
        "primary-fixed-dim": "#5bd7e7",
        "primary": "#d7faff",
        "on-primary-fixed": "#001f23",
        "on-error-container": "#ffdad6",
        "neon-purple": "#A855F7",
        "secondary-fixed-dim": "#cac1ea",
        "secondary-fixed": "#e6deff",
        "surface-container-low": "#171d1d",
        "background-deep": "#130D20",
        "tertiary-fixed-dim": "#edc153",
        "surface-container-high": "#252b2c",
        "surface-glass": "rgba(138, 130, 168, 0.08)",
        "on-surface-variant": "#bcc9cb",
        "on-secondary-fixed": "#1d1736",
        "neon-orange": "#F97316",
        "on-secondary-fixed-variant": "#494264",
        "border-glow": "rgba(110, 232, 248, 0.25)",
        "surface-container-highest": "#303637",
        "error-container": "#93000a",
        "on-tertiary-container": "#765900",
        "on-primary-fixed-variant": "#004f57",
        "on-tertiary-fixed": "#251a00"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        gutter: "24px",
        "container-max": "1440px",
        unit: "4px",
        "margin-desktop": "32px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        sans: ["var(--font-dm-sans)", "ui-sans-serif", "system-ui", "sans-serif"],
        heading: ["var(--font-dm-sans)", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["var(--font-jetbrains-mono)", "ui-monospace", "SFMono-Regular", "monospace"],
        "data-sm": ["var(--font-jetbrains-mono)", "ui-monospace", "SFMono-Regular", "monospace"],
        "body-base": ["var(--font-dm-sans)", "ui-sans-serif", "system-ui", "sans-serif"],
        "label-caps": ["var(--font-jetbrains-mono)", "ui-monospace", "SFMono-Regular", "monospace"],
        "headline-md": ["var(--font-dm-sans)", "ui-sans-serif", "system-ui", "sans-serif"],
        "display-lg": ["var(--font-dm-sans)", "ui-sans-serif", "system-ui", "sans-serif"],
        "data-lg": ["var(--font-jetbrains-mono)", "ui-monospace", "SFMono-Regular", "monospace"]
      },
      fontSize: {
        "data-sm": ["12px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "400" }],
        "body-base": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["10px", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "data-lg": ["20px", { lineHeight: "1.4", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
};
export default config;
